# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181209_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sublist',
            old_name='bname',
            new_name='name',
        ),
    ]
