# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_user_usersub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usersub',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
