# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_asublist_bsublist_tracklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsubList',
        ),
        migrations.DeleteModel(
            name='BsubList',
        ),
        migrations.DeleteModel(
            name='TrackList',
        ),
    ]
