# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_asublist_bsublist_tracklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagA', models.CharField(max_length=15)),
                ('tagB', models.CharField(max_length=15)),
                ('bname', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='AsubList',
        ),
        migrations.DeleteModel(
            name='BsubList',
        ),
    ]
