# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181209_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracklist',
            old_name='tname',
            new_name='name',
        ),
    ]
