# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20181209_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrackList',
        ),
    ]
