# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_tracklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('tag', models.CharField(max_length=1)),
            ],
        ),
    ]
