# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20181209_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('number', models.IntegerField(default=17012345)),
                ('selectTrack', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=17012345)),
                ('subject', models.CharField(max_length=15)),
            ],
        ),
    ]
