# Generated by Django 2.1.4 on 2018-12-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='subject',
        ),
    ]
