# Generated by Django 2.1.4 on 2018-12-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20181210_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
