# Generated by Django 2.1.4 on 2018-12-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20181210_2138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
