# Generated by Django 2.1.4 on 2018-12-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersub',
            name='dummy',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
