# Generated by Django 2.1.4 on 2018-12-13 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_usersub_dummy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSub',
            new_name='Sheet1',
        ),
    ]
