# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-13 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20181213_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=15)),
                ('student', models.IntegerField(default=0)),
                ('rateSum', models.FloatField()),
            ],
        ),
    ]
